name: Build images

on:
  push:
    branches:
      - main

jobs:
  docker-buildx:
    runs-on: self-hosted

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          file: build/Dockerfile
          push: false
          tags: app:latest
