name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: self-hosted

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4