name: Caller Workflow
on: 
  push: 
    branches:
      - development-never
  workflow_dispatch:
jobs:
  scan:
    uses: vinceoa/.github/.github/workflows/scanning.yml@main
    
  build:
    needs: 
      - scan
    uses: vinceoa/.github/.github/workflows/sample-ci.yml@main
    with:
      input1: value1
      input2: ${{vars.OA_BASE_IMAGE}}
