name: Deployer Workflow
on: 
  push: 
    branches:
      - main-never
  workflow_dispatch:
jobs:

  build:
    uses: vinceoa/.github/.github/workflows/builder.yml@main
    with:
      image-type: web


  deploy:
    needs:
      - build
    uses: vinceoa/.github/.github/workflows/deploy.yml@main
    
  slack:
    runs-on: ubuntu-latest
    needs:
      - deploy
      - build

    steps:
      - name: slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "message": "deployer completed"
            }
