name: Deployer Workflow
on: 
  push: 
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    uses: vinceoa/.github/.github/workflows/deploy.yml@main
    
  slack:
    runs-on: ubuntu-latest
    needs:
      - deploy

    steps:
      - name: slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "message": "deployer completed"
            }
